---
title: "Batch Effect Visualization Tool"
output: html_notebook
---

# ! /usr/bin/Rscript
```{r}

# load in the neccessary libraries

library(devtools)
library(kBET)
library(bapred)
library(ggplot2)

# args = commandArgs(trailingOnly=TRUE)

```

Get the dataset, gene counts, etc.

```{r}
data_folder = "C:/Users/Roman/Documents/Work/Depression_and_Immunology/England_Research/Data_No_Filter_Final/dataset_1"
input_counts = "C:/Users/Roman/Documents/Work/Depression_and_Immunology/England_Research/Data_No_Filter_Final/dataset_1/toups_unfiltered_gene_counts.csv"
input_metadata = "C:/Users/Roman/Documents/Work/Depression_and_Immunology/England_Research/Data_No_Filter_Final/dataset_1/toups_unfiltered_metadata.csv"
output_dir = ""
output_name = ""

# Read in data file
my_data <- as.data.frame(t(read.csv(input_counts, header = TRUE, row.names = 1, check.names=FALSE)))

#Read in annotation file
annot <- read.csv(input_annot, header = TRUE, row.names = 1, check.names = FALSE)


```

Call k-BET

```{r}

kbet <- function(gene_counts, metadata) 
{
  batch = annot$batch
  # change this to be factor of interest...
  diagnosis = annot$scid_diagnosis
  # get rid of zero variance genes
  new_data = my_data[ ,which(apply(t(my_data), 1, var) != 0)]

  avedistVal = avedist(new_data, as.factor(batch) )#, as.factor(diagnosis))
  pvcamVal = pvcam(new_data, as.factor(batch), as.factor(diagnosis))
  skewdivVal = skewdiv(new_data, as.factor(batch))
  #sepscoreVal = sepscore(new_data, as.factor(batch) )
  kldistVal = kldist(new_data, as.factor(batch))
  # diffexprmVal = 
  # cobraVal = 
  batch.estimate <- kBET(my_data, batch, plot = FALSE)
  #batch.estimate$results
  #batch.estimate
  #batch.estimate$summary

  # Capitalize Function
  capitalize <- function(x) {
    substr(x, 1, 1) <- toupper(substr(x, 1, 1))
    x
  }
  
  # Generate the Plot title
  plotTitle = paste(capitalize(unlist(strsplit(name, "_"))), collapse= " ")
  
  png(file=paste( output_dir,'/', output_name, ".png", sep=""))
  
  batch.estimate <- kBET(data, batch, plot=FALSE)
  
  plot.data <- data.frame(class=rep(c('observed', 'expected'),
                            each=length(batch.estimate$stats$kBET.observed)), 
                            data =  c(batch.estimate$stats$kBET.observed,
                            batch.estimate$stats$kBET.expected))
  g <- ggplot(plot.data, aes(class, data)) + geom_boxplot() + 
       labs(x='Test', y='Rejection rate',title=paste(plotTitle,'kBET test results',sep=' ')) +
       theme_bw() +  
       scale_y_continuous(limits=c(0,1))
  
  g
  
  dev.off()
  
  results <- batch.estimate$summary
  results['avedist'] = avedistVal
  results['pvcam'] = pvcamVal
  results['skewdiv'] = skewdivVal
  results['kldist'] = kldistVal
  
  results
  
  print('*** DONE WRITING NOW')
  
  write.csv(results, file=paste(output_dir,'/', output_name, "_kBET_results.csv", sep=''))

}

```